services:
  flask-app:
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    networks:
      - backend

  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=game
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrects/db-password
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - backend
    env_file:
      - ./.env

networks:
  backend:


volumes:
  app:
  database:
