services:
  backend:
    build:
      context: .
    restart: unless-stopped
    environment:
      - DB_HOST=localhost
      - DB_NAME=game
      - DB_USER=user
      - DB_PASSWORD=
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    networks:
      - backend

  mysql-db:
    image: mysql:8.0.31
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=game
      - MYSQL_ROOT_PASSWORD=
    ports:
      - "3308:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend
    env_file:
      - ./.env

networks:
  backend:


volumes:
  app:
  database:
