services:
  backend:
    build:
      context: .
    restart: unless-stopped
    environment:
      - DB_HOST=localhost
      - DB_NAME=game
      - DB_USER=user
      - DB_PASSWORD=Kokos1234!
    ports:
      - "5000:5000"
    volumes:
      - game-app:/game_app
    networks:
      - backend_network
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.31
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=game
      - MYSQL_ROOT_PASSWORD=Admin1234!
    ports:
      - "3308:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - mysql_network
    env_file:
      - ./.env

networks:
  backend_network:
  mysql_network:


volumes:
  game-app:
  database:
