services:
  backend:
    build:
      context: .
    restart: unless-stopped
    environment:
      - DB_HOST="${MYSQL_HOST}"
      - DB_NAME="${MYSQL_DB_NAME}"
      - DB_USER="${MYSQL_USERNAME}"
      - DB_PASSWORD="${MYSQL_PASSWORD}"
    ports:
      - "5000:5000"
    volumes:
      - game-app:/game_app
    networks:
      - backend_network
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.31
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE="${MYSQL_DB_NAME}"
      - MYSQL_ROOT_PASSWORD="${MYSQL_PASSWORD}"
    ports:
      - "3308:3306"
    expose:
      - "3306"
    volumes:
      - database:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql_network
    env_file:
      - ./.env

networks:
  backend_network:
  mysql_network:


volumes:
  game-app:
  database:
