version: "3.9"

services:

  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "game"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "game"
    volumes:
      - "./mysql-data:/var/lib/mysql"
